typography_spectrum: 0.5601890962570906
color:
  brandColors:
    - '#2f2f2f'
    - '#939393'
    - '#0e0e0e'
    - '#fdfdfd'
    - '#b0b0b0'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.883829670259729
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74889
analytics:
  google: null
  facebook: null
  twitter: null
name: Fit by 50
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Fit by 50
description: determined to be a better me
purpose: []
